/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortfolioIndexRouteImport } from './routes/_authenticated/portfolio/index'
import { Route as AuthenticatedPortfolioTransactionsRouteImport } from './routes/_authenticated/portfolio/transactions'
import { Route as AuthenticatedPortfolioPnlRouteImport } from './routes/_authenticated/portfolio/pnl'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortfolioIndexRoute =
  AuthenticatedPortfolioIndexRouteImport.update({
    id: '/portfolio/',
    path: '/portfolio/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortfolioTransactionsRoute =
  AuthenticatedPortfolioTransactionsRouteImport.update({
    id: '/portfolio/transactions',
    path: '/portfolio/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortfolioPnlRoute =
  AuthenticatedPortfolioPnlRouteImport.update({
    id: '/portfolio/pnl',
    path: '/portfolio/pnl',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio/pnl': typeof AuthenticatedPortfolioPnlRoute
  '/portfolio/transactions': typeof AuthenticatedPortfolioTransactionsRoute
  '/portfolio/': typeof AuthenticatedPortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio/pnl': typeof AuthenticatedPortfolioPnlRoute
  '/portfolio/transactions': typeof AuthenticatedPortfolioTransactionsRoute
  '/portfolio': typeof AuthenticatedPortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/portfolio/pnl': typeof AuthenticatedPortfolioPnlRoute
  '/_authenticated/portfolio/transactions': typeof AuthenticatedPortfolioTransactionsRoute
  '/_authenticated/portfolio/': typeof AuthenticatedPortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portfolio/pnl'
    | '/portfolio/transactions'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portfolio/pnl'
    | '/portfolio/transactions'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/portfolio/pnl'
    | '/_authenticated/portfolio/transactions'
    | '/_authenticated/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portfolio/': {
      id: '/_authenticated/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof AuthenticatedPortfolioIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portfolio/transactions': {
      id: '/_authenticated/portfolio/transactions'
      path: '/portfolio/transactions'
      fullPath: '/portfolio/transactions'
      preLoaderRoute: typeof AuthenticatedPortfolioTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portfolio/pnl': {
      id: '/_authenticated/portfolio/pnl'
      path: '/portfolio/pnl'
      fullPath: '/portfolio/pnl'
      preLoaderRoute: typeof AuthenticatedPortfolioPnlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPortfolioPnlRoute: typeof AuthenticatedPortfolioPnlRoute
  AuthenticatedPortfolioTransactionsRoute: typeof AuthenticatedPortfolioTransactionsRoute
  AuthenticatedPortfolioIndexRoute: typeof AuthenticatedPortfolioIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPortfolioPnlRoute: AuthenticatedPortfolioPnlRoute,
  AuthenticatedPortfolioTransactionsRoute:
    AuthenticatedPortfolioTransactionsRoute,
  AuthenticatedPortfolioIndexRoute: AuthenticatedPortfolioIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
